# [BeautifulSoup and Requests](https://www.youtube.com/watch?v=bargNl2WeN4&list=PLUaB-1hjhk8G-xVXA5FxT2cLNzd87GInr)

In [4]:
from bs4 import BeautifulSoup
import requests

In [5]:
url = 'https://www.scrapethissite.com/pages/forms/'

In [7]:
page = requests.get(url)

In [15]:
print(page.text)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="hockey">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://www.opensourcesports.com/hockey/" class="data-attribution" target="_blank">http://www.opensourcesports.com/hockey/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row search-area">
                    <div class="col-md-12 text-center">
                        <form method="GET" action="/pages/forms/" class="form form-inline">
                            <label for="q">
                                Search for Teams: &nbsp;
                            </label>
                            <input type="text" class="form-control" name="q" id="q" placeholder="Search for Teams" />

                            <input type="submit" class="btn btn-primary" value="Search" />
                        </form>
                        <hr>
                    </div>
                </div><!--.row.search-area-->


                <table class="table">
                    <tr>
                        <th>
                            Team Name
                        </th>
                        <th>
                            Year
                        </th>
                        <th>
                            Wins
                        </th>
                        <th>
                            Losses
                        </th>
                        <th>
                            OT Losses
                        </th>
                        <th>
                            Win %
                        </th>
                        <th>
                            Goals For (GF)
                        </th>
                        <th>
                            Goals Against (GA)
                        </th>
                        <th>
                            + / -
                        </th>
                    </tr>

                    <tr class="team">
                        <td class="name">
                            Boston Bruins
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            44
                        </td>
                        <td class="losses">
                            24
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.55
                        </td>

                        <td class="gf">
                            299
                        </td>
                        <td class="ga">
                            264
                        </td>


                        <td class="diff text-success">
                            35
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            31
                        </td>
                        <td class="losses">
                            30
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.388
                        </td>

                        <td class="gf">
                            292
                        </td>
                        <td class="ga">
                            278
                        </td>


                        <td class="diff text-success">
                            14
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Calgary Flames
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            46
                        </td>
                        <td class="losses">
                            26
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.575
                        </td>

                        <td class="gf">
                            344
                        </td>
                        <td class="ga">
                            263
                        </td>


                        <td class="diff text-success">
                            81
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Chicago Blackhawks
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            49
                        </td>
                        <td class="losses">
                            23
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.613
                        </td>

                        <td class="gf">
                            284
                        </td>
                        <td class="ga">
                            211
                        </td>


                        <td class="diff text-success">
                            73
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Detroit Red Wings
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            34
                        </td>
                        <td class="losses">
                            38
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.425
                        </td>

                        <td class="gf">
                            273
                        </td>
                        <td class="ga">
                            298
                        </td>


                        <td class="diff text-danger">
                            -25
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Edmonton Oilers
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            37
                        </td>
                        <td class="losses">
                            37
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.463
                        </td>

                        <td class="gf">
                            272
                        </td>
                        <td class="ga">
                            272
                        </td>


                        <td class="diff text-success">
                            0
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Hartford Whalers
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            31
                        </td>
                        <td class="losses">
                            38
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.388
                        </td>

                        <td class="gf">
                            238
                        </td>
                        <td class="ga">
                            276
                        </td>


                        <td class="diff text-danger">
                            -38
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Los Angeles Kings
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            46
                        </td>
                        <td class="losses">
                            24
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-success">
                            0.575
                        </td>

                        <td class="gf">
                            340
                        </td>
                        <td class="ga">
                            254
                        </td>


                        <td class="diff text-success">
                            86
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Minnesota North Stars
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            27
                        </td>
                        <td class="losses">
                            39
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.338
                        </td>

                        <td class="gf">
                            256
                        </td>
                        <td class="ga">
                            266
                        </td>


                        <td class="diff text-danger">
                            -10
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Montreal Canadiens
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            39
                        </td>
                        <td class="losses">
                            30
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.487
                        </td>

                        <td class="gf">
                            273
                        </td>
                        <td class="ga">
                            249
                        </td>


                        <td class="diff text-success">
                            24
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            New Jersey Devils
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            32
                        </td>
                        <td class="losses">
                            33
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.4
                        </td>

                        <td class="gf">
                            272
                        </td>
                        <td class="ga">
                            264
                        </td>


                        <td class="diff text-success">
                            8
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            New York Islanders
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            25
                        </td>
                        <td class="losses">
                            45
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.312
                        </td>

                        <td class="gf">
                            223
                        </td>
                        <td class="ga">
                            290
                        </td>


                        <td class="diff text-danger">
                            -67
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            New York Rangers
                        </td>
                        <td class="year">
                            1990
                        </td>
                        <td class="wins">
                            36
                        </td>
                        <td class="losses">
                            31
                        </td>
                        <td class="ot-losses">

                        </td>


                        <td class="pct text-danger">
                            0.45
                        </td>

                        <td class="gf">
                            297
                        </td>
                        <td class="ga">
                            265
                        </td>



In [11]:
soup = BeautifulSoup(page.text,'html')

In [14]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.55
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        292
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        344
       </td>
       <td class="ga">
        263
       </td>
       <td class="diff text-success">
        81
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        49
       </td>
       <td class="losses">
        23
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.613
       </td>
       <td class="gf">
        284
       </td>
       <td class="ga">
        211
       </td>
       <td class="diff text-success">
        73
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.425
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        298
       </td>
       <td class="diff text-danger">
        -25
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        272
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        238
       </td>
       <td class="ga">
        276
       </td>
       <td class="diff text-danger">
        -38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        340
       </td>
       <td class="ga">
        254
       </td>
       <td class="diff text-success">
        86
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.338
       </td>
       <td class="gf">
        256
       </td>
       <td class="ga">
        266
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.487
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        249
       </td>
       <td class="diff text-success">
        24
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        8
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        25
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.312
       </td>
       <td class="gf">
        223
       </td>
       <td class="ga">
        290
       </td>
       <td class="diff text-danger">
        -67
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        297
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-success">
        32
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.412
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        267
       </td>
       <td class="diff text-danger">
        -15
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        342
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        16
       </td>
       <td class="losses">
        50
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.2
       </td>
       <td class="gf">
        236
       </td>
       <td class="ga">
        354
       </td>
       <td class="diff text-danger">
        -118
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        22
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.588
       </td>
       <td class="gf">
        310
       </td>
       <td class="ga">
        250
       </td>
       <td class="diff text-success">
        60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        23
       </td>
       <td class="losses">
        46
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.287
       </td>
       <td class="gf">
        241
       </td>
       <td class="ga">
        318
       </td>
       <td class="diff text-danger">
        -77
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        28
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.35
       </td>
       <td class="gf">
        243
       </td>
       <td class="ga">
        315
       </td>
       <td class="diff text-danger">
        -72
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        258
       </td>
       <td class="ga">
        258
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.325
       </td>
       <td class="gf">
        260
       </td>
       <td class="ga">
        288
       </td>
       <td class="diff text-danger">
        -28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        270
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-danger">
        -5
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        296
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-danger">
        -9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        257
       </td>
       <td class="ga">
        236
       </td>
       <td class="diff text-success">
        21
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">
          18
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=19">
          19
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=20">
          20
         </a>

Inspecting Web Pages with HTML

Find and Find_all

In [17]:
url = 'https://www.scrapethissite.com/pages/forms/'

In [19]:
page = requests.get(url)

In [20]:
soup = BeautifulSoup(page.text,'html')

In [23]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.55
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        292
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        344
       </td>
       <td class="ga">
        263
       </td>
       <td class="diff text-success">
        81
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        49
       </td>
       <td class="losses">
        23
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.613
       </td>
       <td class="gf">
        284
       </td>
       <td class="ga">
        211
       </td>
       <td class="diff text-success">
        73
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.425
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        298
       </td>
       <td class="diff text-danger">
        -25
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        272
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        238
       </td>
       <td class="ga">
        276
       </td>
       <td class="diff text-danger">
        -38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        340
       </td>
       <td class="ga">
        254
       </td>
       <td class="diff text-success">
        86
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.338
       </td>
       <td class="gf">
        256
       </td>
       <td class="ga">
        266
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.487
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        249
       </td>
       <td class="diff text-success">
        24
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        8
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        25
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.312
       </td>
       <td class="gf">
        223
       </td>
       <td class="ga">
        290
       </td>
       <td class="diff text-danger">
        -67
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        297
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-success">
        32
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.412
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        267
       </td>
       <td class="diff text-danger">
        -15
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        342
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        16
       </td>
       <td class="losses">
        50
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.2
       </td>
       <td class="gf">
        236
       </td>
       <td class="ga">
        354
       </td>
       <td class="diff text-danger">
        -118
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        22
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.588
       </td>
       <td class="gf">
        310
       </td>
       <td class="ga">
        250
       </td>
       <td class="diff text-success">
        60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        23
       </td>
       <td class="losses">
        46
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.287
       </td>
       <td class="gf">
        241
       </td>
       <td class="ga">
        318
       </td>
       <td class="diff text-danger">
        -77
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        28
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.35
       </td>
       <td class="gf">
        243
       </td>
       <td class="ga">
        315
       </td>
       <td class="diff text-danger">
        -72
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        258
       </td>
       <td class="ga">
        258
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.325
       </td>
       <td class="gf">
        260
       </td>
       <td class="ga">
        288
       </td>
       <td class="diff text-danger">
        -28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        270
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-danger">
        -5
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        296
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-danger">
        -9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        257
       </td>
       <td class="ga">
        236
       </td>
       <td class="diff text-success">
        21
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">
          18
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=19">
          19
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=20">
          20
         </a>

In [24]:
soup.find('div')

<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>

In [29]:
soup.find_all('p',class_ ='lead')
# class_ ='col-md-12'

[<p class="lead">
                             Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                         </p>]

In [33]:
soup.find('p',class_ ='lead').text.strip()

'Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.'

In [36]:
soup.find_all('th')

[<th>
                             Team Name
                         </th>,
 <th>
                             Year
                         </th>,
 <th>
                             Wins
                         </th>,
 <th>
                             Losses
                         </th>,
 <th>
                             OT Losses
                         </th>,
 <th>
                             Win %
                         </th>,
 <th>
                             Goals For (GF)
                         </th>,
 <th>
                             Goals Against (GA)
                         </th>,
 <th>
                             + / -
                         </th>]

In [38]:
soup.find('th').text.strip()

'Team Name'

Scraping Data from a Real Website + Pandas

In [ ]:
# import pandas as pd

In [50]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

page = requests.get(url,headers = {"User-Agent":"Mozilla/5.0"})

soup = BeautifulSoup(page.text,'html')

In [53]:
print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of largest companies in the United States by revenue - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"204920ca-b260-447d-9817-919925222c43","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgTitle":"List of largest companies in the United States by revenue","wgCurRevisionId":1354288064,"wgRevisionId":1354288064,"wgArticleId":61181662,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Use mdy dates from April 2025","Economy of the United States-related lists","Lists of companies by revenue","Lists of largest private companies by country","Lists of companies of the United States"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_the_United_States_by_revenue","wgRelevantArticleId":61181662,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":30000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Business":{"class":"List","importance":"Low"},"Finance \u0026 Investment":{"class":"List","importance":"Low"},"Lists":{"class":"List","importance":"Low"},"Project-independent assessment":{"class":"List","importance":""},"United States":{"class":"List","importance":"Low"}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q1860802","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.13" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of largest companies in the United States by revenue - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>
  <link href="auth.wikimedia.org" rel="dns-prefetch"/>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_the_United_States_by_revenue rootpage-List_of_largest_companies_in_the_United_States_by_revenue skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2">
           <a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2">

<table class = ">

<table class="wikitable sortable jquery-tablesorter" id="mwOw">

In [69]:
soup.find('table',class_ ="wikitable sortable" , id = "mwOw")

<table class="wikitable sortable" id="mwOw">
<caption id="mwPA"></caption>
<tbody id="mwPQ"><tr id="mwPg"><th id="mwPw">Rank</th>
<th id="mwQA">Name</th>
<th id="mwQQ">Industry</th>
<th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>
<th id="mwRA">Revenue growth</th>
<th id="mwRQ">Employees</th>
<th id="mwRg">Headquarters</th></tr>
<tr id="mwRw">
<td id="mwSA">1</td>
<td id="mwSQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwSg" rel="mw:WikiLink" title="Walmart">Walmart</a></td>
<td id="mwSw">Retail</td>
<td id="mwTA" style="text-align:center;">680,985</td>
<td id="mwTQ" style="text-align:center;"><span about="#mwt7" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwTg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt8" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwTw" style="display:none" typeof="mw:Transclusion"></span> 5.1%</td>
<td id="mwUA" style="text-align:center;">2,100,000</td>
<td id="mwUQ"><a href="https://en.wikipedia.org/wiki/Bentonville,_Arkansas" id="mwUg" rel="mw:WikiLink" title="Bentonville, Arkansas">Bentonville, Arkansas</a></td></tr>
<tr id="mwUw">
<td id="mwVA">2</td>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwVg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td>
<td id="mwVw">Retail and cloud computing</td>
<td id="mwWA" style="text-align:center;">637,959</td>
<td id="mwWQ" style="text-align:center;"><span about="#mwt9" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt10" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwWw" style="display:none" typeof="mw:Transclusion"></span> 11.0%</td>
<td id="mwXA" style="text-align:center;">1,556,000</td>
<td id="mwXQ"><a href="https://en.wikipedia.org/wiki/Seattle" id="mwXg" rel="mw:WikiLink" title="Seattle">Seattle, Washington</a></td></tr>
<tr id="mwXw">
<td id="mwYA">3</td>
<td id="mwYQ"><a href="https://en.wikipedia.org/wiki/UnitedHealth_Group" id="mwYg" rel="mw:WikiLink" title="UnitedHealth Group">UnitedHealth Group</a></td>
<td id="mwYw">Healthcare</td>
<td id="mwZA" style="text-align:center;">400,278</td>
<td id="mwZQ" style="text-align:center;"><span about="#mwt11" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwZg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt12" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwZw" style="display:none" typeof="mw:Transclusion"></span> 7.7%</td>
<td id="mwaA" style="text-align:center;">400,000</td>
<td id="mwaQ"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwag" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwaw">
<td id="mwbA">4</td>
<td id="mwbQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Apple_Inc" id="mwbg" rel="mw:WikiLink" title="Apple Inc">Apple</a></td>
<td id="mwbw">Technology</td>
<td id="mwcA" style="text-align:center;">391,035</td>
<td id="mwcQ" style="text-align:center;"><span about="#mwt13" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwcg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt14" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwcw" style="display:none" typeof="mw:Transclusion"></span> 2.0%</td>
<td id="mwdA" style="text-align:center;">164,000</td>
<td id="mwdQ"><a href="https://en.wikipedia.org/wiki/Cupertino,_California" id="mwdg" rel="mw:WikiLink" title="Cupertino, California">Cupertino, California</a></td></tr>
<tr id="mwdw">
<td id="mweA">5</td>
<td id="mweQ"><a href="https://en.wikipedia.org/wiki/CVS_Health" id="mweg" rel="mw:WikiLink" title="CVS Health">CVS Health</a></td>
<td id="mwew">Healthcare</td>
<td id="mwfA" style="text-align:center;">372,809</td>
<td id="mwfQ" style="text-align:center;"><span about="#mwt15" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwfg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt16" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwfw" style="display:none" typeof="mw:Transclusion"></span> 4.2%</td>
<td id="mwgA" style="text-align:center;">259,500</td>
<td id="mwgQ"><a href="https://en.wikipedia.org/wiki/Woonsocket,_Rhode_Island" id="mwgg" rel="mw:WikiLink" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a></td></tr>
<tr id="mwgw">
<td id="mwhA">6</td>
<td id="mwhQ"><a href="https://en.wikipedia.org/wiki/Berkshire_Hathaway" id="mwhg" rel="mw:WikiLink" title="Berkshire Hathaway">Berkshire Hathaway</a></td>
<td id="mwhw">Conglomerate</td>
<td id="mwiA" style="text-align:center;">371,433</td>
<td id="mwiQ" style="text-align:center;"><span about="#mwt17" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwig" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt18" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwiw" style="display:none" typeof="mw:Transclusion"></span> 1.9%</td>
<td id="mwjA" style="text-align:center;">392,400</td>
<td id="mwjQ"><a href="https://en.wikipedia.org/wiki/Omaha,_Nebraska" id="mwjg" rel="mw:WikiLink" title="Omaha, Nebraska">Omaha, Nebraska</a></td></tr>
<tr id="mwjw">
<td id="mwkA">7</td>
<td id="mwkQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Alphabet_Inc" id="mwkg" rel="mw:WikiLink" title="Alphabet Inc">Alphabet</a></td>
<td id="mwkw">Technology and cloud computing</td>
<td id="mwlA" style="text-align:center;">350,018</td>
<td id="mwlQ" style="text-align:center;"><span about="#mwt19" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwlg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt20" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwlw" style="display:none" typeof="mw:Transclusion"></span> 13.9%</td>
<td id="mwmA" style="text-align:center;">183,323</td>
<td id="mwmQ"><a href="https://en.wikipedia.org/wiki/Mountain_View,_California" id="mwmg" rel="mw:WikiLink" title="Mountain View, California">Mountain View, California</a></td></tr>
<tr id="mwmw">
<td id="mwnA">8</td>
<td id="mwnQ"><a href="https://en.wikipedia.org/wiki/ExxonMobil" id="mwng" rel="mw:WikiLink" title="ExxonMobil">Exxon Mobil</a></td>
<td id="mwnw">Petroleum</td>
<td id="mwoA" style="text-align:center;">349,595</td>
<td id="mwoQ" style="text-align:center;"><span about="#mwt21" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwog" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt22" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwow" style="display:none" typeof="mw:Transclusion"></span> 1.5%</td>
<td id="mwpA" style="text-align:center;">60,900</td>
<td id="mwpQ"><a href="https://en.wikipedia.org/wiki/Spring,_Texas" id="mwpg" rel="mw:WikiLink" title="Spring, Texas">Spring, Texas</a></td></tr>
<tr id="mwpw">
<td id="mwqA">9</td>
<td id="mwqQ"><a href="https://en.wikipedia.org/wiki/McKesson_Corporation" id="mwqg" rel="mw:WikiLink" title="McKesson Corporation">McKesson Corporation</a></td>
<td id="mwqw">Healthcare</td>
<td id="mwrA" style="text-align:center;">308,951</td>
<td id="mwrQ" style="text-align:center;"><span about="#mwt23" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwrg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt24" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwrw" style="display:none" typeof="mw:Transclusion"></span> 11.7%</td>
<td id="mwsA" style="text-align:center;">48,000</td>
<td id="mwsQ"><a href="https://en.wikipedia.org/wiki/Irving,_Texas" id="mwsg" rel="mw:WikiLink" title="Irving, Texas">Irving, Texas</a></td></tr>
<tr id="mwsw">
<td id="mwtA">10</td>
<td id="mwtQ"><a href="https://en.wikipedia.org/wiki/Cencora" id="mwtg" rel="mw:WikiLink" title="Cencora">Cencora</a></td>
<td id="mwtw">Pharmacy wholesale</td>
<td id="mwuA" style="text-align:center;">293,959</td>
<td id="mwuQ" style="text-align:center;"><span about="#mwt25" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwug" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt26" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwuw" style="display:none" typeof="mw:Transclusion"></span> 12.1%</td>
<td id="mwvA" style="text-align:center;">44,000</td>
<td id="mwvQ"><a href="https://en.wikipedia.org/wiki/Conshohocken,_Pennsylvania" id="mwvg" rel="mw:WikiLink" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a></td></tr>
<tr id="mwvw">
<td id="mwwA">11</td>
<td id="mwwQ"><a href="https://en.wikipedia.org/wiki/JPMorgan_Chase" id="mwwg" rel="mw:WikiLink" title="JPMorgan Chase">JPMorgan Chase</a></td>
<td id="mwww">Financials</td>
<td id="mwxA" style="text-align:center;">278,906</td>
<td id="mwxQ" style="text-align:center;"><span about="#mwt27" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwxg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt28" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwxw" style="display:none" typeof="mw:Transclusion"></span> 16.5%</td>
<td id="mwyA" style="text-align:center;">317,233</td>
<td id="mwyQ"><a href="https://en.wikipedia.org/wiki/New_York_City" id="mwyg" rel="mw:WikiLink" title="New York City">New York City, New York</a></td></tr>
<tr id="mwyw">
<td id="mwzA">12</td>
<td id="mwzQ"><a href="https://en.wikipedia.org/wiki/Costco" id="mwzg" rel="mw:WikiLink" title="Costco">Costco Wholesale</a></td>
<td id="mwzw">Retail</td>
<td id="mw0A" style="text-align:center;">254,453</td>
<td id="mw0Q" style="text-align:center;"><span about="#mwt29" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw0g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt30" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw0w" style="display:none" typeof="mw:Transclusion"></span> 5.0%</td>
<td id="mw1A" style="text-align:center;">333,000</td>
<td id="mw1Q"><a href="https://en.wikipedia.org/wiki/Issaquah,_Washington" id="mw1g" rel="mw:WikiLink" title="Issaquah, Washington">Issaquah, Washington</a></td></tr>
<tr id="mw1w">
<td id="mw2A">13</td>
<td id="mw2Q"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Cigna" id="mw2g" rel="mw:WikiLink" title="Cigna">Cigna</a></td>
<td id="mw2w">Health insurance</td>
<td id="mw3A" style="text-align:center;">247,121</td>
<td id="mw3Q" style="text-align:center;"><span about="#mwt31" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw3g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt32" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw3w" style="display:none" typeof="mw:Transclusion"></span> 26.6%</td>
<td id="mw4A" style="text-align:center;">72,398</td>
<td id="mw4Q"><a href="https://en.wikipedia.org/wiki/Bloomfield,_Connecticut" id="mw4g" rel="mw:WikiLink" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a></td></tr>
<tr id="mw4w">
<td id="mw5A">14</td>
<td id="mw5Q"><a href="https://en.wikipedia.org/wiki/Microsoft" id="mw5g" rel="mw:WikiLink" title="Microsoft">Microsoft</a></td>
<td id="mw5w">Technology and cloud computing</td>
<td id="mw6A" style="text-align:center;">245,122</td>
<td id="mw6Q" style="text-align:center;"><span about="#mwt33" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw6g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt34" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw6w" style="display:none" typeof="mw:Transclusion"></span> 15.7%</td>

In [85]:
table=soup.find_all('table')[0]

In [86]:
print(table)

<table class="wikitable sortable" id="mwOw">
<caption id="mwPA"></caption>
<tbody id="mwPQ"><tr id="mwPg"><th id="mwPw">Rank</th>
<th id="mwQA">Name</th>
<th id="mwQQ">Industry</th>
<th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>
<th id="mwRA">Revenue growth</th>
<th id="mwRQ">Employees</th>
<th id="mwRg">Headquarters</th></tr>
<tr id="mwRw">
<td id="mwSA">1</td>
<td id="mwSQ"><a href="https://en.wikipedia.org/wiki/Walmart" id="mwSg" rel="mw:WikiLink" title="Walmart">Walmart</a></td>
<td id="mwSw">Retail</td>
<td id="mwTA" style="text-align:center;">680,985</td>
<td id="mwTQ" style="text-align:center;"><span about="#mwt7" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwTg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt8" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwTw" style="display:none" typeof="mw:Transclusion"></span> 5.1%</td>
<td id="mwUA" style="text-align:center;">2,100,000</td>
<td id="mwUQ"><a href="https://en.wikipedia.org/wiki/Bentonville,_Arkansas" id="mwUg" rel="mw:WikiLink" title="Bentonville, Arkansas">Bentonville, Arkansas</a></td></tr>
<tr id="mwUw">
<td id="mwVA">2</td>
<td id="mwVQ"><a href="https://en.wikipedia.org/wiki/Amazon_(company)" id="mwVg" rel="mw:WikiLink" title="Amazon (company)">Amazon</a></td>
<td id="mwVw">Retail and cloud computing</td>
<td id="mwWA" style="text-align:center;">637,959</td>
<td id="mwWQ" style="text-align:center;"><span about="#mwt9" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwWg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt10" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwWw" style="display:none" typeof="mw:Transclusion"></span> 11.0%</td>
<td id="mwXA" style="text-align:center;">1,556,000</td>
<td id="mwXQ"><a href="https://en.wikipedia.org/wiki/Seattle" id="mwXg" rel="mw:WikiLink" title="Seattle">Seattle, Washington</a></td></tr>
<tr id="mwXw">
<td id="mwYA">3</td>
<td id="mwYQ"><a href="https://en.wikipedia.org/wiki/UnitedHealth_Group" id="mwYg" rel="mw:WikiLink" title="UnitedHealth Group">UnitedHealth Group</a></td>
<td id="mwYw">Healthcare</td>
<td id="mwZA" style="text-align:center;">400,278</td>
<td id="mwZQ" style="text-align:center;"><span about="#mwt11" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwZg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt12" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwZw" style="display:none" typeof="mw:Transclusion"></span> 7.7%</td>
<td id="mwaA" style="text-align:center;">400,000</td>
<td id="mwaQ"><a href="https://en.wikipedia.org/wiki/Minnetonka,_Minnesota" id="mwag" rel="mw:WikiLink" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a></td></tr>
<tr id="mwaw">
<td id="mwbA">4</td>
<td id="mwbQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Apple_Inc" id="mwbg" rel="mw:WikiLink" title="Apple Inc">Apple</a></td>
<td id="mwbw">Technology</td>
<td id="mwcA" style="text-align:center;">391,035</td>
<td id="mwcQ" style="text-align:center;"><span about="#mwt13" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwcg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt14" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwcw" style="display:none" typeof="mw:Transclusion"></span> 2.0%</td>
<td id="mwdA" style="text-align:center;">164,000</td>
<td id="mwdQ"><a href="https://en.wikipedia.org/wiki/Cupertino,_California" id="mwdg" rel="mw:WikiLink" title="Cupertino, California">Cupertino, California</a></td></tr>
<tr id="mwdw">
<td id="mweA">5</td>
<td id="mweQ"><a href="https://en.wikipedia.org/wiki/CVS_Health" id="mweg" rel="mw:WikiLink" title="CVS Health">CVS Health</a></td>
<td id="mwew">Healthcare</td>
<td id="mwfA" style="text-align:center;">372,809</td>
<td id="mwfQ" style="text-align:center;"><span about="#mwt15" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwfg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt16" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwfw" style="display:none" typeof="mw:Transclusion"></span> 4.2%</td>
<td id="mwgA" style="text-align:center;">259,500</td>
<td id="mwgQ"><a href="https://en.wikipedia.org/wiki/Woonsocket,_Rhode_Island" id="mwgg" rel="mw:WikiLink" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a></td></tr>
<tr id="mwgw">
<td id="mwhA">6</td>
<td id="mwhQ"><a href="https://en.wikipedia.org/wiki/Berkshire_Hathaway" id="mwhg" rel="mw:WikiLink" title="Berkshire Hathaway">Berkshire Hathaway</a></td>
<td id="mwhw">Conglomerate</td>
<td id="mwiA" style="text-align:center;">371,433</td>
<td id="mwiQ" style="text-align:center;"><span about="#mwt17" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwig" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt18" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwiw" style="display:none" typeof="mw:Transclusion"></span> 1.9%</td>
<td id="mwjA" style="text-align:center;">392,400</td>
<td id="mwjQ"><a href="https://en.wikipedia.org/wiki/Omaha,_Nebraska" id="mwjg" rel="mw:WikiLink" title="Omaha, Nebraska">Omaha, Nebraska</a></td></tr>
<tr id="mwjw">
<td id="mwkA">7</td>
<td id="mwkQ"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Alphabet_Inc" id="mwkg" rel="mw:WikiLink" title="Alphabet Inc">Alphabet</a></td>
<td id="mwkw">Technology and cloud computing</td>
<td id="mwlA" style="text-align:center;">350,018</td>
<td id="mwlQ" style="text-align:center;"><span about="#mwt19" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwlg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt20" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwlw" style="display:none" typeof="mw:Transclusion"></span> 13.9%</td>
<td id="mwmA" style="text-align:center;">183,323</td>
<td id="mwmQ"><a href="https://en.wikipedia.org/wiki/Mountain_View,_California" id="mwmg" rel="mw:WikiLink" title="Mountain View, California">Mountain View, California</a></td></tr>
<tr id="mwmw">
<td id="mwnA">8</td>
<td id="mwnQ"><a href="https://en.wikipedia.org/wiki/ExxonMobil" id="mwng" rel="mw:WikiLink" title="ExxonMobil">Exxon Mobil</a></td>
<td id="mwnw">Petroleum</td>
<td id="mwoA" style="text-align:center;">349,595</td>
<td id="mwoQ" style="text-align:center;"><span about="#mwt21" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwog" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt22" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwow" style="display:none" typeof="mw:Transclusion"></span> 1.5%</td>
<td id="mwpA" style="text-align:center;">60,900</td>
<td id="mwpQ"><a href="https://en.wikipedia.org/wiki/Spring,_Texas" id="mwpg" rel="mw:WikiLink" title="Spring, Texas">Spring, Texas</a></td></tr>
<tr id="mwpw">
<td id="mwqA">9</td>
<td id="mwqQ"><a href="https://en.wikipedia.org/wiki/McKesson_Corporation" id="mwqg" rel="mw:WikiLink" title="McKesson Corporation">McKesson Corporation</a></td>
<td id="mwqw">Healthcare</td>
<td id="mwrA" style="text-align:center;">308,951</td>
<td id="mwrQ" style="text-align:center;"><span about="#mwt23" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwrg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt24" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwrw" style="display:none" typeof="mw:Transclusion"></span> 11.7%</td>
<td id="mwsA" style="text-align:center;">48,000</td>
<td id="mwsQ"><a href="https://en.wikipedia.org/wiki/Irving,_Texas" id="mwsg" rel="mw:WikiLink" title="Irving, Texas">Irving, Texas</a></td></tr>
<tr id="mwsw">
<td id="mwtA">10</td>
<td id="mwtQ"><a href="https://en.wikipedia.org/wiki/Cencora" id="mwtg" rel="mw:WikiLink" title="Cencora">Cencora</a></td>
<td id="mwtw">Pharmacy wholesale</td>
<td id="mwuA" style="text-align:center;">293,959</td>
<td id="mwuQ" style="text-align:center;"><span about="#mwt25" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwug" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt26" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwuw" style="display:none" typeof="mw:Transclusion"></span> 12.1%</td>
<td id="mwvA" style="text-align:center;">44,000</td>
<td id="mwvQ"><a href="https://en.wikipedia.org/wiki/Conshohocken,_Pennsylvania" id="mwvg" rel="mw:WikiLink" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a></td></tr>
<tr id="mwvw">
<td id="mwwA">11</td>
<td id="mwwQ"><a href="https://en.wikipedia.org/wiki/JPMorgan_Chase" id="mwwg" rel="mw:WikiLink" title="JPMorgan Chase">JPMorgan Chase</a></td>
<td id="mwww">Financials</td>
<td id="mwxA" style="text-align:center;">278,906</td>
<td id="mwxQ" style="text-align:center;"><span about="#mwt27" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mwxg" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt28" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mwxw" style="display:none" typeof="mw:Transclusion"></span> 16.5%</td>
<td id="mwyA" style="text-align:center;">317,233</td>
<td id="mwyQ"><a href="https://en.wikipedia.org/wiki/New_York_City" id="mwyg" rel="mw:WikiLink" title="New York City">New York City, New York</a></td></tr>
<tr id="mwyw">
<td id="mwzA">12</td>
<td id="mwzQ"><a href="https://en.wikipedia.org/wiki/Costco" id="mwzg" rel="mw:WikiLink" title="Costco">Costco Wholesale</a></td>
<td id="mwzw">Retail</td>
<td id="mw0A" style="text-align:center;">254,453</td>
<td id="mw0Q" style="text-align:center;"><span about="#mwt29" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw0g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt30" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw0w" style="display:none" typeof="mw:Transclusion"></span> 5.0%</td>
<td id="mw1A" style="text-align:center;">333,000</td>
<td id="mw1Q"><a href="https://en.wikipedia.org/wiki/Issaquah,_Washington" id="mw1g" rel="mw:WikiLink" title="Issaquah, Washington">Issaquah, Washington</a></td></tr>
<tr id="mw1w">
<td id="mw2A">13</td>
<td id="mw2Q"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Cigna" id="mw2g" rel="mw:WikiLink" title="Cigna">Cigna</a></td>
<td id="mw2w">Health insurance</td>
<td id="mw3A" style="text-align:center;">247,121</td>
<td id="mw3Q" style="text-align:center;"><span about="#mwt31" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw3g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt32" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw3w" style="display:none" typeof="mw:Transclusion"></span> 26.6%</td>
<td id="mw4A" style="text-align:center;">72,398</td>
<td id="mw4Q"><a href="https://en.wikipedia.org/wiki/Bloomfield,_Connecticut" id="mw4g" rel="mw:WikiLink" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a></td></tr>
<tr id="mw4w">
<td id="mw5A">14</td>
<td id="mw5Q"><a href="https://en.wikipedia.org/wiki/Microsoft" id="mw5g" rel="mw:WikiLink" title="Microsoft">Microsoft</a></td>
<td id="mw5w">Technology and cloud computing</td>
<td id="mw6A" style="text-align:center;">245,122</td>
<td id="mw6Q" style="text-align:center;"><span about="#mwt33" data-mw='{"caption":"Increase","parts":[{"template":{"target":{"wt":"profit","href":"./Template:Profit"},"params":{},"i":0}}]}' id="mw6g" typeof="mw:Transclusion mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-type="drawing" data-file-width="300" decoding="async" height="11" resource="https://en.wikipedia.org/wiki/File:Increase2.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span about="#mwt34" data-mw='{"parts":[{"template":{"target":{"wt":"ntsh","href":"./Template:Ntsh"},"params":{"1":{"wt":"3.0"}},"i":0}}]}' data-sort-value="7000300000000000000♠" id="mw6w" style="display:none" typeof="mw:Transclusion"></span> 15.7%</td>

In [95]:
world_titles = table.find_all('th')

In [96]:
world_titles

[<th id="mwPw">Rank</th>,
 <th id="mwQA">Name</th>,
 <th id="mwQQ">Industry</th>,
 <th id="mwQg">Revenue <br id="mwQw"/>(USD millions)</th>,
 <th id="mwRA">Revenue growth</th>,
 <th id="mwRQ">Employees</th>,
 <th id="mwRg">Headquarters</th>]

In [97]:
world_table_titles= [title.text.strip() for title in world_titles]

In [98]:
world_table_titles

['Rank',
 'Name',
 'Industry',
 'Revenue (USD millions)',
 'Revenue growth',
 'Employees',
 'Headquarters']

In [99]:
import pandas as pd

In [100]:
df = pd.DataFrame(columns=world_table_titles)

In [101]:
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [105]:
column_data = table.find_all('tr')

In [115]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    print(individual_row_data)
    
    length = len(df)
    df.loc[length] =individual_row_data

['1', 'Walmart', 'Retail', '680,985', '5.1%', '2,100,000', 'Bentonville, Arkansas']
['2', 'Amazon', 'Retail and cloud computing', '637,959', '11.0%', '1,556,000', 'Seattle, Washington']
['3', 'UnitedHealth Group', 'Healthcare', '400,278', '7.7%', '400,000', 'Minnetonka, Minnesota']
['4', 'Apple', 'Technology', '391,035', '2.0%', '164,000', 'Cupertino, California']
['5', 'CVS Health', 'Healthcare', '372,809', '4.2%', '259,500', 'Woonsocket, Rhode Island']
['6', 'Berkshire Hathaway', 'Conglomerate', '371,433', '1.9%', '392,400', 'Omaha, Nebraska']
['7', 'Alphabet', 'Technology and cloud computing', '350,018', '13.9%', '183,323', 'Mountain View, California']
['8', 'Exxon Mobil', 'Petroleum', '349,595', '1.5%', '60,900', 'Spring, Texas']
['9', 'McKesson Corporation', 'Healthcare', '308,951', '11.7%', '48,000', 'Irving, Texas']
['10', 'Cencora', 'Pharmacy wholesale', '293,959', '12.1%', '44,000', 'Conshohocken, Pennsylvania']
['11', 'JPMorgan Chase', 'Financials', '278,906', '16.5%', '317,233', 'New York City, New York']
['12', 'Costco Wholesale', 'Retail', '254,453', '5.0%', '333,000', 'Issaquah, Washington']
['13', 'Cigna', 'Health insurance', '247,121', '26.6%', '72,398', 'Bloomfield, Connecticut']
['14', 'Microsoft', 'Technology and cloud computing', '245,122', '15.7%', '228,000', 'Redmond, Washington']
['15', 'Cardinal Health', 'Healthcare', '226,827', '10.6%', '48,411', 'Dublin, Ohio']
['16', 'Chevron', 'Petroleum', '202,792', '0.9%', '45,298', 'Houston, Texas']
['17', 'Bank of America', 'Financials', '192,434', '11.9%', '213,193', 'Charlotte, North Carolina']
['18', 'General Motors', 'Automotive', '187,442', '9.1%', '162,000', 'Detroit, Michigan']
['19', 'Ford Motor', 'Automotive', '184,992', '5.0%', '171,000', 'Dearborn, Michigan']
['20', 'Elevance Health', 'Healthcare', '177,011', '3.3%', '103,679', 'Indianapolis, Indiana']
['21', 'Citigroup', 'Financials', '170,757', '8.9%', '227,855', 'New York City, New York']
['22', 'Meta Platforms', 'Technology', '164,501', '21.9%', '74,067', 'Menlo Park, California']
['23', 'Centene', 'Healthcare', '163,071', '5.9%', '60,500', 'St. Louis, Missouri']
['24', 'The Home Depot', 'Retail', '159,514', '4.5%', '470,100', 'Atlanta, Georgia']
['25', 'Fannie Mae', 'Financials', '152,670', '8.1%', '8,200', 'Washington, D.C.']
['26', 'Walgreens Boots Alliance', 'Pharmaceutical', '147,658', '6.2%', '252,500', 'Deerfield, Illinois']
['27', 'Kroger', 'Retail', '147,123', '-1.9%', '409,000', 'Cincinnati, Ohio']
['28', 'Phillips 66', 'Petroleum', '145,496', '-2.9%', '13,200', 'Houston, Texas']
['29', 'Marathon Petroleum', 'Petroleum', '140,412', '-6.6%', '18,300', 'Findlay, Ohio']
['30', 'Verizon Communications', 'Telecommunications', '134,788', '0.6%', '99,600', 'New York City, New York']
['31', 'Nvidia', 'Technology', '130,497', '114.2%', '36,000', 'Santa Clara, California']
['32', 'Goldman Sachs Group', 'Financials', '126,853', '17.0%', '46,500', 'New York City, New York']
['33', 'Wells Fargo', 'Financials', '125,397', '8.7%', '217,502', 'San Francisco, California']
['34', 'Valero Energy', 'Petroleum', '123,974', '-10.8%', '9,910', 'San Antonio, Texas']
['35', 'Comcast', 'Telecommunications', '123,731', '1.8%', '182,000', 'Philadelphia, Pennsylvania']
['36', 'State Farm Insurance', 'Financials', '122,951', '18.0%', '67,381', 'Bloomington, Illinois']
['37', 'AT&T', 'Conglomerate and telecommunications', '122,336', '-0.1%', '140,990', 'Dallas, Texas']
['38', 'Freddie Mac', 'Financials', '122,052', '13.0%', '8,090', 'McLean, Virginia']
['39', 'Humana', 'Health insurance', '117,761', '10.7%', '65,680', 'Louisville, Kentucky']
['40', 'Morgan Stanley', 'Financials', '107,285', '11.5%', '80,478', 'New York City, New York']
['41', 'Target', 'Retail', '106,566', '-0.8%', '440,000', 'Minneapolis, Minnesota']
['42', 'StoneX Group', 'Financials', '99,888', '64.1%', '4,500', 'New York City, New York']
['43', 'Tesla', 'Automotive and energy', '97,690', '0.9%', '125,665', 'Austin, Texas']
['44', 'Dell Technologies', 'Technology', '95,567', '8.1%', '108,000', 'Round Rock, Texas']
['45', 'PepsiCo', 'Beverage', '91,854', '0.4%', '319,000', 'Purchase, New York']
['46', 'Walt Disney', 'Media', '91,361', '2.8%', '205,040', 'Burbank, California']
['47', 'United Parcel Service', 'Transportation', '91,070', '0.1%', '372,180', 'Atlanta, Georgia']
['48', 'Johnson & Johnson', 'Pharmaceutical', '88,821', '-6.7%', '138,100', 'New Brunswick, New Jersey']
['49', 'FedEx', 'Transportation', '87,693', '-2.7%', '422,100', 'Memphis, Tennessee']
['50', 'Archer Daniels Midland', 'Food industry', '85,530', '-8.9%', '43,213', 'Chicago, Illinois']
['51', 'Procter & Gamble', 'Consumer products manufacturing', '84,039', '2.5%', '108,000', 'Cincinnati, Ohio']
['52', "Lowe's", 'Retail', '83,674', '-3.1%', '215,500', 'Mooresville, North Carolina']
['53', 'Energy Transfer Partners', 'Petroleum', '82,671', '5.2%', '16,248', 'Dallas, Texas']
['54', 'RTX', 'Aerospace and defense', '80,739', '17.1%', '186,000', 'Arlington County, Virginia']
['55', 'Albertsons', 'Retail', '79,238', '2.0%', '196,650', 'Boise, Idaho']
['56', 'Sysco', 'Food processing', '78,844', '3.3%', '76,000', 'Houston, Texas']
['57', 'Progressive', 'Insurance', '75,372', '21.4%', '66,308', 'Mayfield Village, Ohio']
['58', 'American Express', 'Financials', '74,201', '10.1%', '75,100', 'New York City, New York']
['59', 'Lockheed Martin', 'Aerospace and defense', '71,043', '5.1%', '121,000', 'Bethesda, Maryland']
['60', 'MetLife', 'Financials', '70,986', '6.1%', '45,000', 'New York City, New York']
['61', 'HCA Healthcare', 'Healthcare', '70,603', '8.7%', '271,000', 'Nashville, Tennessee']
['62', 'Prudential Financial', 'Financials', '70,405', '30.4%', '37,936', 'Newark, New Jersey']
['63', 'Boeing', 'Aerospace and defense', '66,517', '-14.5%', '172,000', 'Arlington County, Virginia']
['64', 'Caterpillar', 'Machinery', '64,809', '-3.4%', '112,900', 'Irving, Texas']
['65', 'Merck', 'Pharmaceutical industry', '64,168', '6.7%', '74,000', 'Kenilworth, New Jersey']
['66', 'Allstate', 'Insurance', '64,106', '12.3%', '55,200', 'Northfield Township, Illinois']
['67', 'Pfizer', 'Pharmaceutical industry', '63,627', '8.8%', '81,000', 'New York City, New York']
['68', 'IBM', 'Technology and cloud computing', '62,753', '1.4%', '284,500', 'Armonk, New York']
['69', 'New York Life Insurance Company', 'Insurance', '62,639', '15.3%', '15,131', 'New York City, New York']
['70', 'Delta Air Lines', 'Airline', '61,643', '6.2%', '103,000', 'Atlanta, Georgia']
['71', 'Publix Super Markets', 'Retail', '60,177', '4.6%', '255,000', 'Lakeland, Florida']
['72', 'Nationwide Mutual Insurance Company', 'Financials', '58,646', '7.4%', '22,453', 'Columbus, Ohio']
['73', 'TD Synnex', 'Information Technology', '58,452', '1.6%', '25,750', 'Clearwater, Florida']
['74', 'United Airlines Holdings', 'Airline', '57,063', '6.2%', '107,300', 'Chicago, Illinois']
['75', 'ConocoPhillips', 'Petroleum', '56,953', '-2.8%', '11,800', 'Houston, Texas']
['76', 'TJX', 'Retail', '56,360', '4.0%', '364,000', 'Framingham, Massachusetts']
['77', 'AbbVie', 'Pharmaceutical', '56,334', '3.7%', '55,000', 'Lake Bluff, Illinois']
['78', 'Enterprise Products Partners', 'Petroleum', '56,219', '13.1%', '7,800', 'Houston, Texas']
['79', 'Charter Communications', 'Telecommunications', '55,085', '0.9%', '94,500', 'Stamford, Connecticut']
['80', 'Performance Food Group', 'Food processing', '54,681', '2.5%', '36,815', 'Richmond, Virginia']
['81', 'American Airlines Group', 'Airline', '54,211', '2.7%', '133,300', 'Fort Worth, Texas']
['82', 'Capital One Financial', 'Financials', '53,938', '9.0%', '52,600', 'Tysons, Virginia']
['83', 'Cisco Systems', 'Telecom hardware manufacturing', '53,803', '-5.6%', '90,400', 'San Jose, California']
['84', 'HP', 'Technology', '53,559', '-0.3%', '58,000', 'Palo Alto, California']
['85', 'Tyson Foods', 'Food processing', '53,309', '0.8%', '138,000', 'Springdale, Arkansas']
['86', 'Intel', 'Technology', '53,101', '-2.1%', '108,900', 'Santa Clara, California']
['87', 'Oracle', 'Technology', '52,961', '6.0%', '159,000', 'Austin, Texas']
['88', 'Broadcom', 'Technology', '52,432', '46.4%', '37,000', 'Palo Alto, California']
['89', 'Deere', 'Agriculture manufacturing', '51,716', '-15.6%', '55,524', 'Moline, Illinois']
['90', 'Nike', 'Apparel', '51,361', '0.3%', '78,400', 'Beaverton, Oregon']
['91', 'Liberty Mutual Insurance Group', 'Insurance', '50,429', '-4.1%', '40,000', 'Boston, Massachusetts']
['92', 'Plains GP Holdings', 'Petroleum', '50,073', '2.8%', '4,200', 'Houston, Texas']
['93', 'USAA', 'Insurance', '48,560', '14.3%', '38,018', 'San Antonio, Texas']
['94', 'Bristol-Myers Squibb', 'Pharmaceutical', '48,300', '7.3%', '34,100', 'New York City, New York']
['95', 'Ingram Micro Holding', 'Technology', '47,984', '-0.1%', '26,125', 'Irvine, California']
['96', 'General Dynamics', 'Aerospace and defense', '47,716', '12.9%', '117,000', 'Reston, Virginia']
['97', 'Coca-Cola', 'Beverage', '47,061', '2.9%', '69,700', 'Atlanta, Georgia']
['98', 'TIAA', 'Financials', '46,946', '2.6%', '15,623', 'New York City, New York']
['99', 'Travelers', 'Insurance', '46,423', '12.2%', '34,000', 'New York City, New York']
['100', 'Eli Lilly', 'Pharmaceutical', '45,043', '32.0%', '47,000', 'Indianapolis, Indiana']

In [116]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [118]:
df.to_csv(r'/mnt/g/facultate/anul 3 sem 2/Practica de specialiate/L6-Generative AI & RAG Systems/Companies.csv',index =False)

# [How to Scrape Wikipedia With Python | Web Scraping Tutorial](https://www.youtube.com/watch?v=tcSdNWWrlK8)

`pip install requests beautifulsoup4 lxml html2text pandas`

In [ ]:
import requests
from bs4 import BeautifulSoup
import html2text
import pandas as pd
import io,os,re,json,random
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

USER_AGENTS = [
    "Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36"
]

[Web scraping from Wikipedia using Python -GFG](https://www.geeksforgeeks.org/python/web-scraping-from-wikipedia-using-python-a-complete-guide/)

In [48]:
import requests

url = "https://en.wikipedia.org/wiki/Main_Page"
headers = {
    "User-Agent": "Mozilla/5.0"
}
page = requests.get(url, headers=headers)
print(page.status_code)
print(page.content)

200

In [49]:
from bs4 import BeautifulSoup
import requests

url  = "https://en.wikipedia.org/wiki/Main_Page"
headers = {
    "User-Agent": "Mozilla/5.0"
}
page = requests.get(url,headers=headers)
soup = BeautifulSoup(page.content, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-disabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-not-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Wikipedia, the free encyclopedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-disabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-feature-navigation-update-disabled vector-sticky-header-enabled vector-toc-not-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"ad630cfb-c9dd-4f9e-bae6-3246408ea637","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Main_Page","wgTitle":"Main Page","wgCurRevisionId":1358980925,"wgRevisionId":1358980925,"wgArticleId":15580374,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Main_Page","wgRelevantArticleId":15580374,"wgTempUserName":null,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["sysop"],"wgRestrictionMove":["sysop"],"wgIsMainPage":true,"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":3000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q5296","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","mediawiki.skinning.content.parsoid":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","mediawiki.skins.legacy":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.parsermigration.reportbug.init","site","mediawiki.page.ready","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cmediawiki.skinning.content.parsoid%7Cmediawiki.skins.legacy%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.13" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Yeah_Yeah_Yeahs_Coachella_2006.jpg/1280px-Yeah_Yeah_Yeahs_Coachella_2006.jpg?utm_source=en.wikipedia.org&amp;utm_campaign=index&amp;utm_content=thumbnail" property="og:image"/>
  <meta content="1200" property="og:image:width"/>
  <meta content="709" property="og:image:height"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="Wikipedia, the free encyclopedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/api.php?action=featuredfeed&amp;feed=potd&amp;feedformat=atom" rel="alternate" title="Wikipedia picture of the day feed" type="application/atom+xml"/>
  <link href="/w/api.php?action=featuredfeed&amp;feed=featured&amp;feedformat=atom" rel="alternate" title="Wikipedia featured articles feed" type="application/atom+xml"/>
  <link href="/w/api.php?action=featuredfeed&amp;feed=onthisday&amp;feedformat=atom" rel="alternate" title="Wikipedia &amp;quot;On this day...&amp;quot; feed" type="application/atom+xml"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/Main_Page" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>
  <link href="auth.wikimedia.org" rel="dns-prefetch"/>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Main_Page rootpage-Main_Page skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2">
           <a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2">
           <a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Main+Page" title="You are encouraged to create an account and log in; however, it is not mandatory">
            <span>
             Create account
            </span>
           </a>
          </li>
          <li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2">
           <a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=Main+Page" title="You're encouraged to log in; however, it's not mandatory. [o]">